config/routes.rb
Trails::Application.routes.draw do
  resources :maps  do
    resources :start_points
  end

  resources :games do
    resources :algorithms
    patch 'bot', to: 'games#bot'
    resources :rounds
  end
  delete 'games/:game_id/algorithms/:id/remove', to: 'algorithms#remove', as: 'game_algorithm_remove'

  get 'games/:id/start' => 'games#start'

  get 'about' => 'games#about'

  root 'games#index'

  

end

app/models/map.rb
class Map < ActiveRecord::Base
  has_many :games
  has_many :start_points

  validates :min, :width, :height,
            presence: true
  validates :width, numericality: {greater_than: 3}
  validates :height, numericality: {greater_than: 3}

  def prettyname
    "min: #{min}\t max: #{max}\t width: #{width}\t height: #{height}"
  end

  def start_points_valid?
    self.start_points.count >= self.min
  end

  def max
    start_points.count
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:min, :width, :height)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.slim
= simple_form_for @map do |f|
  - if @map.errors.any?
    #error_explanation
      h2 = "#{pluralize(@map.errors.count, "error")} prohibited this map from being saved:"
      ul
        - @map.errors.full_messages.each do |message|
          li = message

  = f.input :min
  = f.input :width
  = f.input :height
  .actions = f.submit 'Save', class: ['btn', 'btn-primary']

app/views/maps/edit.html.slim
h1 Editing map

== render 'form'

= link_to 'Show', @map
'|
= link_to 'Back', maps_path

app/views/maps/index.html.slim
h1 Listing maps

table.table.table-striped
  tr
    th Min
    th Width
    th Height
    th Points
    th
    th

  - @maps.each do |map|
    tr
      td = map.min
      td = map.width
      td = map.height
      td = link_to 'Points', map_start_points_path(map)
      td = link_to 'Edit', edit_map_path(map)
      td = link_to 'Destroy', map, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Map', new_map_path

app/views/maps/new.html.slim
h1 New map

== render 'form'

= link_to 'Back', maps_path

app/views/maps/show.html.slim
p#notice = notice

p
  strong Min:
  = @map.min
p
  strong Width:
  = @map.width
p
  strong Height:
  = @map.height

= link_to 'Edit', edit_map_path(@map)
'|
= link_to 'Back', maps_path