config/routes.rb
Trails::Application.routes.draw do
  resources :maps  do
    resources :start_points
  end

  resources :games do
    resources :algorithms
    patch 'bot', to: 'games#bot'
    resources :rounds
  end
  delete 'games/:game_id/algorithms/:id/remove', to: 'algorithms#remove', as: 'game_algorithm_remove'

  get 'games/:id/start' => 'games#start'

  get 'about' => 'games#about'

  root 'games#index'

  

end

app/models/algorithm.rb
class Algorithm < ActiveRecord::Base
  has_and_belongs_to_many :games
  has_many :algorithm_steps
  has_many :steps, through: :algorithm_steps

  validate :code_validity
  validates :code,
            presence: true

  def name
    "#{id} #{description}"
  end

  private
  def code_validity
    true
  end
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  before_action :set_algorithm, only: [:show, :edit, :update, :destroy, :remove]
  before_action :set_game, only: [:create, :edit, :new, :update, :show, :remove]

  # GET /algorithms
  # GET /algorithms.json
  def index
    @algorithms = Algorithm.all
  end

  # GET /algorithms/1
  # GET /algorithms/1.json
  def show
  end

  # GET /algorithms/new
  def new
    @algorithm = Algorithm.new
  end

  # GET /algorithms/1/edit
  def edit
  end

  # POST /algorithms
  # POST /algorithms.json
  def create
    ap @game
    @algorithm = Algorithm.new(algorithm_params)
    @algorithm.games << @game

    respond_to do |format|
      if @algorithm.save
        format.html { redirect_to game_path(@game), notice: 'Algorithm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @algorithm }
      else
        ap @algorithm
        format.html { render action: 'new' }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /algorithms/1
  # PATCH/PUT /algorithms/1.json
  def update
    respond_to do |format|
      if @algorithm.update(algorithm_params)
        format.html { redirect_to @game, notice: 'Algorithm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algorithms/1
  # DELETE /algorithms/1.json
  def destroy
    @algorithm.destroy
    respond_to do |format|
      format.html { redirect_to game_algorithms_url }
      format.json { head :no_content }
    end
  end

  def remove
    @game.algorithms.delete(@algorithm)
    redirect_to game_path(@game), :notice => 'Algorithm was removed from the game'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_algorithm
    @algorithm = Algorithm.find(params[:id])
  end

  def set_game
    @game = Game.find(params[:game_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def algorithm_params
    params.require(:algorithm).permit(:bot, :code, :description)
  end
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/views/algorithms/_bots_form.html.slim
= simple_form_for @game, url:  game_bot_path(@game) do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  .form-inputs
    =select_tag 'bot_id', options_from_collection_for_select(bots, 'id', 'name')
  .form-actions
    .actions = f.submit 'Submit Bot', class: ['btn', 'btn-primary']

app/views/algorithms/_form.html.slim
= simple_form_for [@game, algorithm] do |f|
  - if algorithm.errors.any?
    #error_explanation
      h2 = "#{pluralize(algorithm.errors.count, "error")} prohibited this algorithm from being saved:"
      ul
        - algorithm.errors.full_messages.each do |message|
          li = message
  = f.error_notification

  .form-inputs
    = f.input :bot, label: 'Save?'
    = f.input :code
    = f.input :description
  .form-actions
    .actions = f.submit 'Submit New Algorithm', class: ['btn', 'btn-primary']

app/views/algorithms/edit.html.slim
h1 Editing algorithm

== render 'form', algorithm: @algorithm

= link_to 'Show', game_algorithm_path(@game, @algorithm)
'|
= link_to 'Back', game_algorithms_path(@game)

app/views/algorithms/index.html.slim
h1 Listing algorithms

table
  tr
    th Bot
    th
    th
    th

  - @algorithms.each do |algorithm|
    tr
      td = algorithm.bot
      td = link_to 'Show', algorithm
      td = link_to 'Edit', edit_algorithm_path(algorithm)
      td = link_to 'Destroy', algorithm, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Algorithm', new_algorithm_path

app/views/algorithms/new.html.slim
h1 New algorithm

== render 'form'

= link_to 'Back', algorithms_path

app/views/algorithms/show.html.slim
p#notice = notice

p
  strong Bot:
  = @algorithm.bot

= link_to 'Edit', edit_game_algorithm_path(@game, @algorithm)
'|
= link_to 'Back', game_algorithms_path