config/routes.rb
Trails::Application.routes.draw do
  resources :maps  do
    resources :start_points
  end

  resources :games do
    resources :algorithms
    patch 'bot', to: 'games#bot'
    resources :rounds
  end
  delete 'games/:game_id/algorithms/:id/remove', to: 'algorithms#remove', as: 'game_algorithm_remove'

  get 'games/:id/start' => 'games#start'

  get 'about' => 'games#about'

  root 'games#index'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :map
  has_many :rounds

  has_and_belongs_to_many :algorithms

  validates :map,
            presence: true
  validates :name,
            presence: true,
            uniqueness: true,
            allow_blank: false
  validates :status, inclusion: { in: %w(new started finished)}
  validates :rounds_num, presence: true, numericality: {greater_than: 0}

  def active?
    status == 'new'
  end

  def winner
    max_points = -999999
    current = nil
    scores.each { |k,v|
      if v > max_points
        current = k
        max_points = v
      end
    }
    current
  end

  def scores
    player_scores = {}

    algorithms.each { |a|
      player_scores[a] = 0
    }

    rounds.each { |r|
      round_scores = r.scores
      round_scores.each { |k,v|
        player_scores[k] += v
      }
    }

    player_scores
  end

  def has_min_players?
    self.algorithms.count >= self.map.min
  end

  def map_full?
    self.algorithms.count >= self.map.max
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :start]

  def about
    @team = ['Michał Knapik', 'Jakub Liput', 'Krzysztof Romanowski', 'Dawid Kala', 'Marcin Haręza', 'Piotr Styrna']
    @team.shuffle!
  end

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @algorithm = Algorithm.new
    @current_algorithms = @game.algorithms
    @bots = Algorithm.where(:bot => true)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def bot
    @game = Game.find(params[:game_id])
    bots = Algorithm.where(:id => params[:bot_id])
    if bots.empty?
      redirect_to @game, flash: {error: 'No bot selected'}
      return
    end
    if @game.map_full?
      redirect_to @game, flash: {error: 'Map is already full'}
      return
    end
    if bots.first.in? @game.algorithms
      redirect_to @game, flash: {error: 'Cant reuse this bot'}
      return
    end
    @game.algorithms << bots.first
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Bot was added to game.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { redirect_to @game, flash: {error: 'Bot was not added'} }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end


  def start
    if @game.status != 'new'

      redirect_to @game, flash: {error: 'Game already started'}
    elsif not @game.has_min_players?
      redirect_to @game, flash: {error: 'Not enough players'}
    else


      g = GameEngine.new @game
      g.start

      #Thread.new do
      #  puts "start thread --------------------"
      #  Rails.logger.info("start thread --------------------")
      #  g.start
      #end

      redirect_to game_path(@game)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :map_id, :rounds_num)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_algorithm_list.html.slim
.container
  .span4
    table.table.table-striped
      tr
        th id
        th Bot
        th Desc
        th

      - algorithms.each do |algorithm|
        tr
          td = link_to algorithm.id, [@game, algorithm]
          td = algorithm.bot
          td = algorithm.description
          td = link_to 'delete', game_algorithm_remove_path(@game, algorithm), :confirm => 'Are you sure?', :method => :delete
    br

app/views/games/_form.html.slim
= simple_form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  .form-inputs
    = f.input :name
    = f.association :map, :as => :collection_select, collection: Map.all.select { |map| map.start_points_valid? }, label_method: :prettyname
    = f.input :rounds_num
  .form-actions
    .actions = f.submit 'Save', class: ['btn', 'btn-primary']

app/views/games/_rounds.html.slim
h3 Listing rounds

table.table.table-striped
  tr
    th no
    th results
    - @game.algorithms.each do |algorithm|
      th = algorithm.id

  - rounds.each do |round|
    tr
      td = round.number
      td = link_to 'Show', game_round_path(@game, round)
      - @game.algorithms.each do |algorithm|
        td = round.scores[algorithm]

table.table.table-stripped
  tr
    th = 'And the winner is '  + @game.winner.id.to_s
br

app/views/games/about.html.slim
.container
  .row

    .span6
      p
        'This application was developed during the course of
        'Software Development Methods at University of Science and Technology
        'by the following team:
        ul
          - @team.each do |member|
            li= member
  .row
    .span6
      'To get more info about <b>Trails</b> visit
      = link_to 'project wiki', 'https://www.assembla.com/spaces/agh-trails/wiki'
      '
      'at Assembla.
br
br

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'|
= link_to 'Back', games_path

app/views/games/index.html.slim
h1 Listing games

table.table.table-striped
  tr
    th Name
    th Map
    th Rounds
    th Status
    th
    th
    th

  - @games.each do |game|
    tr
      td = game.name
      td = game.map.prettyname
      td = game.rounds_num
      td = game.status
      td = link_to 'Show', game
      td = link_to 'Edit', edit_game_path(game)
      td = link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Game', new_game_path

app/views/games/new.html.slim
h1 New game

== render 'form'

= link_to 'Back', games_path

app/views/games/show.html.slim
p#notice = notice

.container
  .row
    dl.dl-horizontal
      dt Name:
      dd= @game.name
      dt Map:
      dd= @game.map.prettyname
      dt Status:
      dd= @game.status
      dt Number of rounds:
      dd= @game.rounds_num
      dt Status
      dd= @game.status

.container
  .row
    .span6
      == render 'algorithm_list', algorithms: @current_algorithms
    - unless @game.active?
      .span6
        == render 'rounds', rounds: @game.rounds
  .row
    - if @game.active?
      .span6
        == render 'algorithms/form', algorithm: @algorithm

      .span6
        == render 'algorithms/bots_form', algorithm: @algorithm, bots: @bots

  .row
    - if @game.has_min_players?   and  @game.active?
      == link_to 'Start', :action => 'start'

p


= link_to 'Edit', edit_game_path(@game)
'|
= link_to 'Back', games_path