config/routes.rb
Trails::Application.routes.draw do
  resources :maps  do
    resources :start_points
  end

  resources :games do
    resources :algorithms
    patch 'bot', to: 'games#bot'
    resources :rounds
  end
  delete 'games/:game_id/algorithms/:id/remove', to: 'algorithms#remove', as: 'game_algorithm_remove'

  get 'games/:id/start' => 'games#start'

  get 'about' => 'games#about'

  root 'games#index'

  

end

app/models/start_point.rb
class StartPoint < ActiveRecord::Base
  belongs_to :map

  validates :x, :y, presence: true
  validates :x, uniqueness: {scope: [:map, :y]}
end

app/controllers/start_points_controller.rb
class StartPointsController < ApplicationController
  before_action :set_start_point, only: [:show, :edit, :update, :destroy]
  before_action :set_map

  # GET /start_points
  # GET /start_points.json
  def index
    @start_points = StartPoint.where(map_id: @map.id)
  end

  # GET /start_points/1
  # GET /start_points/1.json

  # GET /start_points/new
  def new
    @start_point = StartPoint.new
  end

  # GET /start_points/1/edit
  def edit
  end

  # POST /start_points
  # POST /start_points.json
  def create
    @start_point = StartPoint.new(start_point_params)
    @start_point.map = @map

    respond_to do |format|
      if @start_point.save
        format.html { redirect_to map_start_points_path(@map), notice: 'start_point was successfully created.' }
        format.json { render action: 'show', status: :created, location: @start_point }
      else
        format.html { render action: 'new' }
        format.json { render json: @start_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /start_points/1
  # PATCH/PUT /start_points/1.json
  def update
    respond_to do |format|
      if @start_point.update(start_point_params)
        format.html { redirect_to map_start_points_path(@map), notice: 'start_point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @start_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /start_points/1
  # DELETE /start_points/1.json
  def destroy
    @start_point.destroy
    respond_to do |format|
      format.html { redirect_to map_start_points_path(@map) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_start_point
      @start_point = StartPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def start_point_params
      params.require(:start_point).permit(:x, :y)
    end

    def set_map
      @map = Map.find(params[:map_id])
    end
end

app/views/start_points/_form.html.slim
= simple_form_for [@map, @start_point] do |f|
  - if @start_point.errors.any?
    #error_explanation
      h2 = "#{pluralize(@start_point.errors.count, "error")} prohibited this map from being saved:"
      ul
        - @start_point.errors.full_messages.each do |message|
          li = message

  = f.input :x, collection: 1..(@map.width-2)
  = f.input :y, collection: 1..(@map.height-2)
  .actions = f.submit 'Save', class: ['btn', 'btn-primary']

app/views/start_points/edit.html.slim
h1 Editing map

== render 'form'

= link_to 'Show', @map
'|
= link_to 'Back', maps_path

app/views/start_points/index.html.slim
h1 Listing start points

table.table.table-striped
  tr
    th X
    th Y
    th
    th
    th

  - @start_points.each do |start_point|
    tr
      td = start_point.x
      td = start_point.y
      td = link_to 'Edit', edit_map_start_point_path(@map, start_point)
      td = link_to 'Destroy', map_start_point_path(@map, start_point), :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Point', new_map_start_point_path(@map)
'|
= link_to 'Map', maps_path(@map)

app/views/start_points/new.html.slim
h1 New start point

== render 'form'

= link_to 'Back', map_start_points_path(@map)